rapsheet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('raptweets.urls', namespace='raptweets')),
    url(r'^admin/', include(admin.site.urls))
]

raptweets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^albums/(?P<album_id>[0-9]+)/tweets/', views.tweets, name='tweets'),
    url(r'^albums/(?P<album_id>[0-9]+)/graph/', views.graph, name='graph'),
    url(r'^artists/(?P<artist_id>[0-9]+)/tweets/', views.artist_tweets, name='artist_tweets'),
    url(r'^artists/(?P<artist_id>[0-9]+)/albums/', views.artist_albums, name='artist_albums'),
    url(r'^artists/graph', views.artist_graph, name='artist_graph'),
    url(r'^search/', views.search, name='search'),
    url(r'^artists/', views.artists, name='artists'),
    url(r'^albums/', views.albums, name='albums'),
    url(r'^background/', views.background, name='background')
]

raptweets/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=100)
    artist = models.ForeignKey(Artist)
    release_date = models.DateTimeField()
    image_url = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.artist.name + ' - ' + self.title

    class Meta:
        unique_together = ('artist', 'title')

class Tweet(models.Model):
    text = models.CharField(max_length=140, unique=True)
    sentiment = models.FloatField()
    pub_date = models.DateTimeField('date published')
    album = models.ForeignKey(Album)

    def __str__(self):
        return str(self.text)


# TODO more relevant tweets
# TODO styling
# TODO if tweets already loaded, do not make another query (i.e. coming from graph view)

raptweets/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import IntegrityError

import json

from .models import *
from . import engine

def index(request):
    return render_to_response('raptweets/index.html')

"""
Views for albums
"""

"""
The search view. Returns a list of albums to match the search query.
"""
def search(request):
    query = request.GET.get('q')
    if query:
        results = engine.get_results(query)
        album_list = []
        for item in results:
            try:
                album, created = Album.objects.get_or_create(
                    title=item['name'],
                    artist=Artist.objects.get_or_create(name=item['artist'],
                                                        image_url=engine.get_image(item['artist']))[0],
                    release_date=engine.format_date(item['release_date']),
                    image_url=item['image_url']
                )
            except IntegrityError:
                continue
            if album not in album_list:
                album_list.append(album)
        return render(request, 'raptweets/results.html', {
            'results': album_list,
            'query': query
        })
    return HttpResponse('404')

"""
The tweets view. Allows one to look at all the tweets about a particular album.
"""
def tweets(request, album_id):
    album = get_object_or_404(Album, pk=album_id)                       # Query
    engine.search_and_add_tweets(album)
    tweet_list = Tweet.objects.filter(album=album).order_by('-pub_date')
    paginator = Paginator(tweet_list, 10)
    page = request.GET.get('page')
    try:
        t = paginator.page(page)
    except PageNotAnInteger:
        t = paginator.page(1)
    except EmptyPage:
        t = paginator.page(paginator.num_pages)
    return render(request, 'raptweets/tweets.html', {
        'tweets': t,
        'album': album,
        'pages': [num for num in range(1, t.paginator.num_pages)]
    })

"""
Similar to the tweets view, the graph view generates a D3.js scatterplot of the average
tweet sentiment per day.
"""
def graph(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    engine.search_and_add_tweets(album)
    avg = engine.average_sentiment_per_day(Tweet.objects.filter(album=album)
                                                        .order_by('pub_date'))  # Query
    return render(request, 'raptweets/graph.html', {
        'album': album,
        'avg': json.dumps(avg)
    })

def albums(request):
    return render(request, 'raptweets/albums.html', {
        'albums': Album.objects.all().order_by('title')
    })

"""
Views for artists
"""

"""
All of the tweets about a particular artist
"""
def artist_tweets(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    tweet_list = engine.get_artist_tweets(artist)
    paginator = Paginator(tweet_list, 10)
    page = request.GET.get('page')
    try:
        t = paginator.page(page)
    except PageNotAnInteger:
        t = paginator.page(1)
    except EmptyPage:
        t = paginator.page(paginator.num_pages)
    return render(request, 'raptweets/artist_tweets.html', {
        'artist': artist,
        'tweets': t,
        'pages': [num for num in range(1, t.paginator.num_pages)]
    })

"""
All of the albums for a particular artist
"""
def artist_albums(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    album_list = artist.album_set.all().order_by('release_date')
    return render(request, 'raptweets/artist_albums.html', {
        'artist': artist,
        'albums': album_list,
    })

"""
All of the artists
"""
def artists(request):
    return render(request, 'raptweets/artists.html', {
        'artists': Artist.objects.all().order_by('name'),
        'engine': engine
    })

"""
A D3.js visualization of how much people are tweeting about each artist (In Progress).
"""
def artist_graph(request):
    result = engine.construct_matrix()
    return render(request, 'raptweets/artist_graph.html', {
        'result': json.dumps(result)
    })

"""
Other views
"""

"""
To run in the background and gather tweets
"""
def background(request):
    while True:
        for album in Album.objects.all():
            engine.search_and_add_tweets(album)
            print(album.title)
        print(Tweet.objects.count())
    return graph(request, 1)

raptweets/templates/raptweets/albums.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Albums</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav class="nav-justified navbar-right">
        <ul class="nav nav-pills ">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <h1>All Albums</h1>
    <div class="albums">
    {% for album in albums %}
        <div id="album">
            <h3><a href="{%  url 'raptweets:artist_albums' album.artist.id %}">{{ album.artist.name }}</a> - <a href="{% url 'raptweets:graph' album.id %}">{{ album.title }}</a></h3>
            <h4>Released: {{ album.release_date }}</h4>
            <img src="{{  album.image_url }}">
        </div>
    {% endfor %}
    </div>
</body>
</html>

raptweets/templates/raptweets/artist_albums.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Albums for {{ artist.name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav>
        <ul class="nav nav-pills">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <h1>Albums for {{ artist.name }}</h1>
    <div class="albums">
    {% for album in albums %}
        <div id="album">
            <h3>Title: <a href="{%  url 'raptweets:graph' album.id %}">{{ album.title }}</a></h3>
            <h4>Release Date: {{ album.release_date }}</h4>
            <img src="{{  album.image_url }}">
        </div>
    {% endfor %}
    </div>
</body>
</html>

raptweets/templates/raptweets/artist_graph.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Artist Visualization</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script type="text/javascript" src="{% static 'raptweets/artist.js' %}"></script>
</head>
<body>
    <nav>
        <ul class="nav nav-pills">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <div id="data">
        {{ result }}
    </div>
</body>
</html>

raptweets/templates/raptweets/artist_tweets.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Tweets for {{ artist.name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav class="nav-justified navbar-right">
        <ul class="nav nav-pills ">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <br/><br/>
    <h1>Tweets for {{ artist.name }} </h1>
    <div class="tweets">
    {% for tweet in tweets %}
        <div id="tweet">
            Tweet: {{  tweet.text }} <br>
            Date: {{ tweet.pub_date }} <br>
            Sentiment: {{ tweet.sentiment }}
        </div>
    {% endfor %}
    </div>
    <div class="page">
        <ul class="pagination">
            {% if tweets.has_previous %}
                <li><a href="{{ tweets.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for num in pages %}
                <li><a href="?page={{ num }}">{{ num }}</a></li>
            {% endfor %}
            {% if tweets.has_next %}
                <li><a href="?page={{ tweets.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
</body>
</html>

raptweets/templates/raptweets/artists.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Artists</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav class="nav-justified navbar-right">
        <ul class="nav nav-pills ">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <h1>All Artists</h1>
    <div class="artists">
    {% for artist in artists %}
        <div id="artist">
            <h3>Name: <a href="{% url 'raptweets:artist_albums' artist.id %}">{{ artist.name }}</a></h3>
            <img src="{{ artist.image_url }}">
        </div>
    {% endfor %}
    </div>
</body>
</html>

raptweets/templates/raptweets/graph.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Graph</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.6.7/d3-tip.min.js"></script>
    <script type="text/javascript" src="{% static 'raptweets/graph.js' %}"></script>
</head>
<body>
    <nav>
        <ul class="nav nav-pills">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
            <li><a href="{% url 'raptweets:tweets' album.id %}">Tweets for this album</a></li>
        </ul>
    </nav>
    <h1>Graph for {{ album.title }} - <a href="{% url 'raptweets:artist_albums' album.artist_id %}">{{ album.artist.name }}</a></h1>
    <div id="avg">
        {{ avg }}
    </div>
    <div class="graph"></div>
</body>
</html>

raptweets/templates/raptweets/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
</head>
<body>
    <nav>
        <ul class="nav nav-pills">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <h1>RapTweets</h1>
    <h2>Search for an album to see its graph</h2>
    <div class="jumbotron">
        <div class="container">
            <div class="form">
                <form action="{% url 'raptweets:search' %}" method="get">
                    <input type="text" name="q" id="searchbar" placeholder="search">
                    <input type="submit" value="Search" id="button"><br>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

raptweets/templates/raptweets/results.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Search Results</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav>
        <ul class="nav nav-pills">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
        </ul>
    </nav>
    <h1>Results for: {{ query }}</h1>
    <div class="albums">
        {% for album in results %}
        <div id="album">
            <h3><a href="{%  url 'raptweets:artist_albums' album.artist.id %}">{{ album.artist }}</a> - <a href="{% url 'raptweets:graph' album.id %}">{{ album.title }}</a></h3>
            <h3>Released: {{ album.release_date }}</h3>
            <img src="{{ album.image_url }}">
        </div>
        {% endfor %}
    </div>
</body>
</html>

raptweets/templates/raptweets/tweets.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Tweets</title>
    <link rel="stylesheet" type="text/css" href="{% static 'raptweets/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav class="nav-justified navbar-right">
        <ul class="nav nav-pills ">
            <li><a href="{% url 'raptweets:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'raptweets:artists' %}">Artists</a></li>
            <li><a href="{% url 'raptweets:albums' %}">Albums</a></li>
            <li><a href="{% url 'raptweets:artist_graph' %}">Artist Visualization</a></li>
            <li><a href="{% url 'raptweets:graph' album.id %}">Graph for this album</a></li>
        </ul>
    </nav>
    <br/><br/>
    <h1>Tweets for <a href="{% url 'raptweets:artist_albums' album.artist_id %}">{{ album.artist.name }}</a> - {{ album.title }}</h1>
    <div class="tweets">
    {% for tweet in tweets %}
        <div id="tweet">
            Tweet: {{  tweet.text }} <br>
            Date: {{ tweet.pub_date }} <br>
            Sentiment: {{ tweet.sentiment }}
        </div>
    {% endfor %}
    </div>
    <div class="page">
        <ul class="pagination">
            {% if tweets.has_previous %}
                <li><a href="{{ tweets.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for num in pages %}
                <li><a href="?page={{ num }}">{{ num }}</a></li>
            {% endfor %}
            {% if tweets.has_next %}
                <li><a href="?page={{ tweets.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
</body>
</html>